#!/usr/bin/env bash

cd "$(dirname "$0")"

path_root="$(dirname "$0")"
path_cookies="$path_root/cookies.txt"
path_user_agent="$path_root/user_agent.txt"
path_base_url="$path_root/base_url.txt"
path_result="$path_root/result"
path_log_anonymous="$path_root/result/log-anonymous.txt"
path_log_registered="$path_root/result/log-registered.txt"
path_site="$path_root/result/files"
path_site_anonymous="$path_root/result/files/anonymous"
path_site_registered="$path_root/result/files/registered"

user_agent=$(<$path_user_agent)
base_url=$(<$path_base_url)

rm -rf $path_result

mkdir $path_result
mkdir $path_site
touch $path_log_anonymous
touch $path_log_registered

wget --recursive \
     --level=100 \
     --directory-prefix=$path_site_anonymous \
     --append-output=$path_log_anonymous \
     --default-page=index \
     $base_url

wget --recursive \
     --level=100 \
     --directory-prefix=$path_site_registered \
     --append-output=$path_log_registered \
     --load-cookies=$path_cookies \
     --keep-session-cookies \
     --default-page=index \
     --user-agent="$user_agent" \
     $base_url